# Generated by Django 4.1.1 on 2022-10-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0003_alter_attack_attacker_alter_attack_victim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='succesful',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='type_attack',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='victim',
        ),
    ]
