# Generated by Django 4.1.1 on 2022-10-04 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0004_remove_attack_created_at_remove_attack_succesful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='succesful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='type_attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attack',
            name='victim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim_pay', to='ptit_dej.tomorrowteam'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='attacker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_ransom', to='ptit_dej.tomorrowteam'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
