# Generated by Django 4.1.1 on 2022-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0005_attack_created_at_attack_succesful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomorrowteam',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
