# Generated by Django 4.1.1 on 2022-10-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0007_alter_tomorrowteam_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petitdej',
            old_name='onslaught',
            new_name='attaque',
        ),
        migrations.RenameField(
            model_name='petitdej',
            old_name='consumable',
            new_name='consomable',
        ),
    ]
