# Generated by Django 4.1.1 on 2022-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0008_rename_onslaught_petitdej_attaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitdej',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
