# Generated by Django 4.1.1 on 2022-10-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0009_alter_petitdej_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomorrowteam',
            name='picture',
            field=models.ImageField(null=True, upload_to='image_profile'),
        ),
    ]
