# Generated by Django 4.1.2 on 2022-10-18 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptit_dej', '0013_tomorrowteam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomorrowteam',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tomorrowteam',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tomorrowteam',
            name='password',
        ),
        migrations.AddField(
            model_name='tomorrowteam',
            name='code',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='tomorrowteam',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tomorrowteam', to=settings.AUTH_USER_MODEL),
        ),
    ]
