# Generated by Django 4.1.2 on 2022-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0014_remove_tomorrowteam_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomorrowteam',
            name='code',
            field=models.CharField(max_length=18),
        ),
    ]
