# Generated by Django 4.1.2 on 2022-10-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0015_alter_tomorrowteam_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitdej',
            name='consomable',
        ),
    ]
