# Generated by Django 4.1.2 on 2022-10-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0016_remove_petitdej_consomable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitdej',
            name='attaque',
        ),
    ]
