# Generated by Django 4.1.2 on 2022-10-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0017_remove_petitdej_attaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitdej',
            name='attaque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PetitDej_Pay', to='ptit_dej.attack'),
        ),
        migrations.AddField(
            model_name='petitdej',
            name='consomable',
            field=models.ManyToManyField(to='ptit_dej.consumable'),
        ),
    ]
