# Generated by Django 4.1.2 on 2022-10-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptit_dej', '0018_petitdej_attaque_petitdej_consomable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(choices=[('PAC', 'pain au chocolat'), ('CRO', 'Croissant'), ('JDO', "jus d'orange"), ('JDP', 'Jus de pomme'), ('COO', 'Café'), ('MAISON', 'maison')], default='COO', max_length=10),
        ),
    ]
